const premiumTranslations = {
  es: { eyebrow: 'Lylo Premium', title: 'Más posibilidades para tu comunidad.', intro: 'Elige el plan que mejor encaje con tu servidor. Los beneficios están en camino.', planOne: 'Plan 1', planTwo: 'Plan 2', soon: 'Próximamente', bestValue: 'Mejor valor', month: '/ mes', year: '/ año', planOneText: 'Una forma sencilla de darle un impulso a tu servidor.', planTwoText: 'La experiencia completa para comunidades que quieren crecer.', benefitOne: 'Funciones premium para tu comunidad', benefitTwo: 'Más opciones de configuración', benefitThree: 'Soporte para tu servidor', benefitFour: 'Todo lo incluido en el Plan 1', benefitFive: 'Beneficios exclusivos próximamente', benefitSix: 'Prioridad para nuevas funciones', buy: 'Comprar', footnote: 'Los planes todavía están en preparación. Te avisaremos cuando estén disponibles.' },
  en: { eyebrow: 'Lylo Premium', title: 'More possibilities for your community.', intro: 'Choose the plan that fits your server. Benefits are on the way.', planOne: 'Plan 1', planTwo: 'Plan 2', soon: 'Coming soon', bestValue: 'Best value', month: '/ month', year: '/ year', planOneText: 'A simple way to give your server a lift.', planTwoText: 'The complete experience for communities ready to grow.', benefitOne: 'Premium features for your community', benefitTwo: 'More configuration options', benefitThree: 'Support for your server', benefitFour: 'Everything in Plan 1', benefitFive: 'Exclusive benefits coming soon', benefitSix: 'Priority for new features', buy: 'Buy', footnote: 'Plans are still in preparation. We will let you know when they are available.' },
  fr: { eyebrow: 'Lylo Premium', title: 'Plus de possibilités pour votre communauté.', intro: 'Choisissez le plan adapté à votre serveur. Les avantages arrivent bientôt.', planOne: 'Plan 1', planTwo: 'Plan 2', soon: 'Bientôt disponible', bestValue: 'Meilleur choix', month: '/ mois', year: '/ an', planOneText: 'Une façon simple de donner un nouvel élan à votre serveur.', planTwoText: 'L’expérience complète pour les communautés prêtes à grandir.', benefitOne: 'Fonctions Premium pour votre communauté', benefitTwo: 'Plus d’options de configuration', benefitThree: 'Assistance pour votre serveur', benefitFour: 'Tout le contenu du Plan 1', benefitFive: 'Avantages exclusifs bientôt disponibles', benefitSix: 'Priorité sur les nouvelles fonctions', buy: 'Acheter', footnote: 'Les plans sont encore en préparation. Nous vous préviendrons dès leur disponibilité.' },
  pt: { eyebrow: 'Lylo Premium', title: 'Mais possibilidades para sua comunidade.', intro: 'Escolha o plano ideal para seu servidor. Os benefícios estão a caminho.', planOne: 'Plano 1', planTwo: 'Plano 2', soon: 'Em breve', bestValue: 'Melhor valor', month: '/ mês', year: '/ ano', planOneText: 'Uma forma simples de dar um impulso ao seu servidor.', planTwoText: 'A experiência completa para comunidades prontas para crescer.', benefitOne: 'Recursos Premium para sua comunidade', benefitTwo: 'Mais opções de configuração', benefitThree: 'Suporte para seu servidor', benefitFour: 'Tudo incluído no Plano 1', benefitFive: 'Benefícios exclusivos em breve', benefitSix: 'Prioridade para novos recursos', buy: 'Comprar', footnote: 'Os planos ainda estão em preparação. Avisaremos quando estiverem disponíveis.' },
  id: { eyebrow: 'Lylo Premium', title: 'Lebih banyak kemungkinan untuk komunitasmu.', intro: 'Pilih paket yang cocok untuk servermu. Manfaatnya segera hadir.', planOne: 'Paket 1', planTwo: 'Paket 2', soon: 'Segera hadir', bestValue: 'Nilai terbaik', month: '/ bulan', year: '/ tahun', planOneText: 'Cara sederhana untuk meningkatkan servermu.', planTwoText: 'Pengalaman lengkap untuk komunitas yang siap berkembang.', benefitOne: 'Fitur Premium untuk komunitasmu', benefitTwo: 'Lebih banyak pilihan pengaturan', benefitThree: 'Dukungan untuk servermu', benefitFour: 'Semua yang ada di Paket 1', benefitFive: 'Manfaat eksklusif segera hadir', benefitSix: 'Prioritas untuk fitur baru', buy: 'Beli', footnote: 'Paket masih dalam persiapan. Kami akan memberi tahu saat tersedia.' },
  de: { eyebrow: 'Lylo Premium', title: 'Mehr Möglichkeiten für deine Community.', intro: 'Wähle den passenden Plan für deinen Server. Die Vorteile kommen bald.', planOne: 'Plan 1', planTwo: 'Plan 2', soon: 'Demnächst', bestValue: 'Bester Wert', month: '/ Monat', year: '/ Jahr', planOneText: 'Eine einfache Möglichkeit, deinen Server zu stärken.', planTwoText: 'Das komplette Erlebnis für wachsende Communities.', benefitOne: 'Premium-Funktionen für deine Community', benefitTwo: 'Mehr Konfigurationsmöglichkeiten', benefitThree: 'Support für deinen Server', benefitFour: 'Alles aus Plan 1', benefitFive: 'Exklusive Vorteile kommen bald', benefitSix: 'Priorität für neue Funktionen', buy: 'Kaufen', footnote: 'Die Pläne werden noch vorbereitet. Wir informieren dich, sobald sie verfügbar sind.' }
};

function applyPremiumLanguage(code) {
  const copy = premiumTranslations[code] || premiumTranslations.es;
  document.querySelectorAll('[data-premium]').forEach((element) => {
    const value = copy[element.dataset.premium];
    if (value) element.textContent = value;
  });
}

applyPremiumLanguage(localStorage.getItem('lylo-site-language') || localStorage.getItem('lylo-language') || 'es');
document.addEventListener('lylo-language-change', (event) => applyPremiumLanguage(event.detail));
