const languages = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'es', label: 'Español', flag: '🇲🇽' },
  { code: 'pt', label: 'Português', flag: '🇧🇷' },
  { code: 'id', label: 'Indonesia', flag: '🇮🇩' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' }
];

const translations = {
  es: { navPremium: 'Premium✦', login: 'Iniciar sesión', support: 'Soporte', logout: 'Cerrar sesión', inviteButton: 'Añadir bot', manageServers: 'Gestionar servidores', heroText: 'La forma más simple de hacer que tu comunidad se sienta viva, organizada y lista para crecer.', premiumEyebrow: 'Muy pronto', premiumTitle: 'Lleva tu servidor un paso más allá.', premiumText: 'Premium reunirá herramientas avanzadas, más control y experiencias especiales para las comunidades que quieren algo extraordinario.', premiumStatus: 'En preparación', featuresEyebrow: 'Todo lo que tu comunidad necesita', featuresTitle: 'Más control para tu servidor. Más tiempo para tu comunidad.', featureOneTitle: 'Moderación', featureOneText: 'Actúa rápido frente a mensajes, usuarios o situaciones que rompen el ambiente de tu servidor.', featureTwoTitle: 'AutoMod', featureTwoText: 'Detecta spam, enlaces peligrosos y palabras bloqueadas automáticamente, incluso cuando nadie está mirando.', featureThreeTitle: 'Tickets', featureThreeText: 'Crea un canal privado para soporte, reportes o solicitudes y atiende cada caso con orden.', featureFourTitle: 'Bienvenidas', featureFourText: 'Recibe a cada persona con un mensaje claro, roles automáticos y toda la información que necesita.', featureFiveTitle: 'Despedidas', featureFiveText: 'Mantén informado al servidor cuando alguien se vaya y conserva una comunidad que se siente cuidada.', featureSixTitle: 'Roles y comunidad', featureSixText: 'Organiza intereses, permisos y accesos para que cada miembro encuentre su lugar.', storyEyebrow: 'Pensado para personas', storyTitle: 'La tecnología puede sentirse cercana.', storyText: 'Lylo reúne las herramientas importantes de tu servidor en un solo lugar, con decisiones fáciles de entender y una interfaz que no se interpone en la conversación.', storyDetail: 'Conecta tu cuenta, configura tu comunidad y deja que el bot haga su parte. Tú mantienes el control.', storyLink: 'Conocer Lylo', closingEyebrow: 'Un comienzo sencillo', closingTitle: 'Tu servidor merece un bot que entienda el ambiente.', closingLink: 'Empezar con Lylo', terms: 'Términos', policy: 'Política de privacidad' },
  en: { navFeatures: 'Features', navAbout: 'About Lylo', navInvite: 'Add to Discord', login: 'Link account', support: 'Support', logout: 'Log out', eyebrow: 'Your community, in good hands', heroTitle: 'Make your server feel like home.', heroText: 'Lylo is a simple, reliable Discord bot built to care for your community, keep it organized, and give every conversation its place.', inviteButton: 'Add bot', exploreButton: 'Explore features', heroNote: 'Simple setup. No noise.', previewOnline: 'Lylo is ready', previewTag: 'your trusted bot', previewMessage: 'Hello, I am here to help.', previewCommand: 'configure your server', featuresEyebrow: 'Everything in its place', featuresTitle: 'Less friction. More community.', featureOneTitle: 'Clear moderation', featureOneText: 'Tools designed to keep your space welcoming without turning it into a maze of settings.', featureTwoTitle: 'Roles and welcome', featureTwoText: 'Give everyone an organized first experience and help them find their place from minute one.', featureThreeTitle: 'Built to grow', featureThreeText: 'Lylo grows with your server as a small group becomes a real community.', closingEyebrow: 'A simple beginning', closingTitle: 'Your server deserves a bot that understands the room.', closingLink: 'Start with Lylo', terms: 'Terms', policy: 'Privacy policy' },
  fr: { navFeatures: 'Fonctions', navAbout: 'À propos', navInvite: 'Ajouter à Discord', eyebrow: 'Votre communauté, entre de bonnes mains', heroTitle: 'Faites de votre serveur un chez-soi.', heroText: 'Lylo est un bot Discord simple et fiable pour prendre soin de votre communauté et garder chaque conversation à sa place.', inviteButton: 'Ajouter bot', exploreButton: 'Voir les fonctions', heroNote: 'Configuration simple. Sans bruit.', previewOnline: 'Lylo est prêt', previewTag: 'votre bot de confiance', previewMessage: 'Bonjour, je suis là pour aider.', previewCommand: 'configurer votre serveur', featuresEyebrow: 'Tout à sa place', featuresTitle: 'Moins de complications. Plus de communauté.', featureOneTitle: 'Modération claire', featureOneText: 'Des outils pour garder un espace agréable sans le transformer en labyrinthe de réglages.', featureTwoTitle: 'Rôles et accueil', featureTwoText: 'Offrez à chacun une première expérience organisée et chaleureuse.', featureThreeTitle: 'Prêt à grandir', featureThreeText: 'Lylo accompagne votre serveur au fil de sa croissance.', closingEyebrow: 'Un début simple', closingTitle: 'Votre serveur mérite un bot qui comprend l’ambiance.', closingLink: 'Commencer avec Lylo', terms: 'Conditions', policy: 'Confidentialité' },
  pt: { navFeatures: 'Recursos', navAbout: 'Sobre Lylo', navInvite: 'Adicionar ao Discord', eyebrow: 'Sua comunidade em boas mãos', heroTitle: 'Faça seu servidor parecer uma casa.', heroText: 'Lylo é um bot do Discord simples e confiável para cuidar da comunidade e manter cada conversa no seu lugar.', inviteButton: 'Adicionar bot', exploreButton: 'Conhecer recursos', heroNote: 'Configuração simples. Sem ruído.', previewOnline: 'Lylo está pronto', previewTag: 'seu bot de confiança', previewMessage: 'Olá, estou aqui para ajudar.', previewCommand: 'configure seu servidor', featuresEyebrow: 'Tudo no lugar', featuresTitle: 'Menos complicação. Mais comunidade.', featureOneTitle: 'Moderação clara', featureOneText: 'Ferramentas para manter um espaço agradável sem um labirinto de configurações.', featureTwoTitle: 'Cargos e boas-vindas', featureTwoText: 'Receba cada pessoa com uma experiência organizada desde o primeiro minuto.', featureThreeTitle: 'Feito para crescer', featureThreeText: 'Lylo acompanha seu servidor enquanto ele se transforma em uma comunidade.', closingEyebrow: 'Um começo simples', closingTitle: 'Seu servidor merece um bot que entende o ambiente.', closingLink: 'Começar com Lylo', terms: 'Termos', policy: 'Privacidade' },
  id: { navFeatures: 'Fitur', navAbout: 'Tentang Lylo', navInvite: 'Tambahkan ke Discord', eyebrow: 'Komunitasmu di tangan yang tepat', heroTitle: 'Buat servermu terasa seperti rumah.', heroText: 'Lylo adalah bot Discord yang sederhana dan andal untuk menjaga komunitas dan merapikan setiap percakuhan.', inviteButton: 'Tambahkan bot', exploreButton: 'Lihat fitur', heroNote: 'Pengaturan mudah. Tanpa gangguan.', previewOnline: 'Lylo siap', previewTag: 'bot tepercaya', previewMessage: 'Halo, aku siap membantu.', previewCommand: 'atur servermu', featuresEyebrow: 'Semuanya pada tempatnya', featuresTitle: 'Lebih sedikit masalah. Lebih banyak komunitas.', featureOneTitle: 'Moderasi jelas', featureOneText: 'Alat untuk menjaga ruang tetap nyaman tanpa pengaturan yang membingungkan.', featureTwoTitle: 'Peran dan sambutan', featureTwoText: 'Berikan pengalaman pertama yang rapi untuk semua orang.', featureThreeTitle: 'Siap berkembang', featureThreeText: 'Lylo tumbuh bersama servermu.', closingEyebrow: 'Awal yang sederhana', closingTitle: 'Servermu layak mendapatkan bot yang memahami suasana.', closingLink: 'Mulai dengan Lylo', terms: 'Ketentuan', policy: 'Privasi' },
  de: { navFeatures: 'Funktionen', navAbout: 'Über Lylo', navInvite: 'Zu Discord hinzufügen', eyebrow: 'Deine Community in guten Händen', heroTitle: 'Mach deinen Server zu einem Zuhause.', heroText: 'Lylo ist ein einfacher und zuverlässiger Discord-Bot für deine Community und klare Gespräche.', inviteButton: 'Bot hinzufügen', exploreButton: 'Funktionen entdecken', heroNote: 'Einfache Einrichtung. Kein Lärm.', previewOnline: 'Lylo ist bereit', previewTag: 'dein vertrauenswürdiger Bot', previewMessage: 'Hallo, ich bin hier, um zu helfen.', previewCommand: 'Server einrichten', featuresEyebrow: 'Alles an seinem Platz', featuresTitle: 'Weniger Aufwand. Mehr Community.', featureOneTitle: 'Klare Moderation', featureOneText: 'Werkzeuge für einen angenehmen Raum ohne ein Labyrinth aus Einstellungen.', featureTwoTitle: 'Rollen und Begrüßung', featureTwoText: 'Gib allen von Anfang an eine klare und freundliche Erfahrung.', featureThreeTitle: 'Bereit zu wachsen', featureThreeText: 'Lylo wächst mit deinem Server.', closingEyebrow: 'Ein einfacher Anfang', closingTitle: 'Dein Server verdient einen Bot, der die Stimmung versteht.', closingLink: 'Mit Lylo starten', terms: 'Bedingungen', policy: 'Datenschutz' }
};

const communityTranslations = {
  es: { communityEyebrow: 'Una comunidad que crece', communityTitle: 'Comunidades que confían en nosotros', communityLive: 'En vivo', communityEmpty: 'Todavía no hay comunidades para mostrar.', communityMembers: 'Miembros' },
  en: { communityEyebrow: 'A growing community', communityTitle: 'Communities that trust us', communityLive: 'Live', communityEmpty: 'There are no communities to show yet.', communityMembers: 'Members' },
  fr: { communityEyebrow: 'Une communauté grandissante', communityTitle: 'Les communautés qui nous font confiance', communityLive: 'En direct', communityEmpty: 'Aucune communauté à afficher pour le moment.', communityMembers: 'Membres' },
  pt: { communityEyebrow: 'Uma comunidade em crescimento', communityTitle: 'Comunidades que confiam em nós', communityLive: 'Ao vivo', communityEmpty: 'Ainda não há comunidades para mostrar.', communityMembers: 'Membros' },
  id: { communityEyebrow: 'Komunitas yang terus berkembang', communityTitle: 'Komunitas yang mempercayai kami', communityLive: 'Langsung', communityEmpty: 'Belum ada komunitas untuk ditampilkan.', communityMembers: 'Anggota' },
  de: { communityEyebrow: 'Eine wachsende Community', communityTitle: 'Communities, die uns vertrauen', communityLive: 'Live', communityEmpty: 'Noch gibt es keine Communities zu sehen.', communityMembers: 'Mitglieder' }
};

const legalTranslations = {
  es: {
    legalBack: '← Volver a Lylo', termsTitle: 'Términos de servicio', termsUpdated: 'Última actualización: 21 de septiembre de 2026', policyTitle: 'Política de privacidad', policyUpdated: 'Última actualización: 21 de septiembre de 2026', notFoundEyebrow: 'Página no encontrada', notFoundTitle: 'Este lugar todavía no existe.', notFoundText: 'Puede que el enlace haya cambiado o que la página esté descansando. Regresa al inicio y continuemos desde ahí.', goBackHome: 'Volver a Lylo', notFoundCode: '404'
  },
  en: {
    legalBack: '← Back to Lylo', termsTitle: 'Terms of service', termsUpdated: 'Last updated: September 21, 2026', policyTitle: 'Privacy policy', policyUpdated: 'Last updated: September 21, 2026', notFoundEyebrow: 'Page not found', notFoundTitle: 'This place does not exist yet.', notFoundText: 'The link may have changed or the page may be resting. Go back home and let’s continue from there.', goBackHome: 'Back to Lylo', notFoundCode: '404'
  },
  fr: {
    legalBack: '← Retour à Lylo', termsTitle: 'Conditions d’utilisation', termsUpdated: 'Dernière mise à jour : 21 septembre 2026', policyTitle: 'Politique de confidentialité', policyUpdated: 'Dernière mise à jour : 21 septembre 2026', notFoundEyebrow: 'Page introuvable', notFoundTitle: 'Cet endroit n’existe pas encore.', notFoundText: 'Le lien a peut-être changé ou la page est en pause. Reviens à l’accueil et continuons.', goBackHome: 'Retour à Lylo', notFoundCode: '404'
  },
  pt: {
    legalBack: '← Voltar para Lylo', termsTitle: 'Termos de serviço', termsUpdated: 'Última atualização: 21 de setembro de 2026', policyTitle: 'Política de privacidade', policyUpdated: 'Última atualização: 21 de setembro de 2026', notFoundEyebrow: 'Página não encontrada', notFoundTitle: 'Este lugar ainda não existe.', notFoundText: 'O link pode ter mudado ou a página está em descanso. Volte ao início e continuemos.', goBackHome: 'Voltar para Lylo', notFoundCode: '404'
  },
  id: {
    legalBack: '← Kembali ke Lylo', termsTitle: 'Syarat layanan', termsUpdated: 'Terakhir diperbarui: 21 September 2026', policyTitle: 'Kebijakan privasi', policyUpdated: 'Terakhir diperbarui: 21 September 2026', notFoundEyebrow: 'Halaman tidak ditemukan', notFoundTitle: 'Tempat ini belum ada.', notFoundText: 'Tautannya mungkin berubah atau halaman sedang istirahat. Kembali ke beranda dan lanjutkan dari sana.', goBackHome: 'Kembali ke Lylo', notFoundCode: '404'
  },
  de: {
    legalBack: '← Zurück zu Lylo', termsTitle: 'Nutzungsbedingungen', termsUpdated: 'Letzte Aktualisierung: 21. September 2026', policyTitle: 'Datenschutzerklärung', policyUpdated: 'Letzte Aktualisierung: 21. September 2026', notFoundEyebrow: 'Seite nicht gefunden', notFoundTitle: 'Dieser Ort existiert noch nicht.', notFoundText: 'Der Link wurde wahrscheinlich geändert oder die Seite ruht gerade. Geh zurück zur Startseite und fangen wir dort an.', goBackHome: 'Zurück zu Lylo', notFoundCode: '404'
  }
};

const completeTranslations = {
  es: { navPremium: 'Premium✦', login: 'Iniciar sesión', support: 'Soporte', logout: 'Cerrar sesión', inviteButton: 'Añadir bot', manageServers: 'Gestionar servidores', heroText: 'La forma más simple de hacer que tu comunidad se sienta viva, organizada y lista para crecer.', communityEyebrow: 'Una comunidad que crece', communityTitle: 'Comunidades que confían en nosotros', communityLive: 'En vivo', communityEmpty: 'Todavía no hay comunidades para mostrar.', communityMembers: 'Miembros', featuresEyebrow: 'Todo lo que tu comunidad necesita', featuresTitle: 'Más control para tu servidor. Más tiempo para tu comunidad.', featureOneTitle: 'Moderación', featureOneText: 'Actúa rápido frente a mensajes, usuarios o situaciones que rompen el ambiente de tu servidor.', featureTwoTitle: 'AutoMod', featureTwoText: 'Detecta spam, enlaces peligrosos y palabras bloqueadas automáticamente, incluso cuando nadie está mirando.', featureThreeTitle: 'Tickets', featureThreeText: 'Crea un canal privado para soporte, reportes o solicitudes y atiende cada caso con orden.', featureFourTitle: 'Bienvenidas', featureFourText: 'Recibe a cada persona con un mensaje claro, roles automáticos y toda la información que necesita.', featureFiveTitle: 'Despedidas', featureFiveText: 'Mantén informado al servidor cuando alguien se vaya y conserva una comunidad que se siente cuidada.', featureSixTitle: 'Roles y comunidad', featureSixText: 'Organiza intereses, permisos y accesos para que cada miembro encuentre su lugar.', premiumEyebrow: 'Muy pronto', premiumTitle: 'Lleva tu servidor un paso más allá.', premiumText: 'Premium reunirá herramientas avanzadas, más control y experiencias especiales para las comunidades que quieren algo extraordinario.', premiumStatus: 'En preparación', storyEyebrow: 'Pensado para personas', storyTitle: 'La tecnología puede sentirse cercana.', storyText: 'Lylo reúne las herramientas importantes de tu servidor en un solo lugar, con decisiones fáciles de entender y una interfaz que no se interpone en la conversación.', storyDetail: 'Conecta tu cuenta, configura tu comunidad y deja que el bot haga su parte. Tú mantienes el control.', storyLink: 'Conocer Lylo', closingEyebrow: 'Un comienzo sencillo', closingTitle: 'Tu servidor merece un bot que entienda el ambiente.', closingLink: 'Empezar con Lylo', terms: 'Términos', policy: 'Política de privacidad' },
  en: { navPremium: 'Premium✦', login: 'Log in', support: 'Support', logout: 'Log out', inviteButton: 'Add bot', manageServers: 'Manage servers', heroText: 'The simplest way to make your community feel alive, organized, and ready to grow.', communityEyebrow: 'A growing community', communityTitle: 'Communities that trust us', communityLive: 'Live', communityEmpty: 'There are no communities to show yet.', communityMembers: 'Members', featuresEyebrow: 'Everything your community needs', featuresTitle: 'More control for your server. More time for your community.', featureOneTitle: 'Moderation', featureOneText: 'Act quickly when messages, users, or situations disrupt your server.', featureTwoTitle: 'AutoMod', featureTwoText: 'Automatically catch spam, dangerous links, and blocked words, even when nobody is watching.', featureThreeTitle: 'Tickets', featureThreeText: 'Create private channels for support, reports, and requests, and handle every case with clarity.', featureFourTitle: 'Welcomes', featureFourText: 'Greet every member with a clear message, automatic roles, and the information they need.', featureFiveTitle: 'Goodbyes', featureFiveText: 'Keep your server informed when someone leaves and make your community feel cared for.', featureSixTitle: 'Roles and community', featureSixText: 'Organize interests, permissions, and access so everyone can find their place.', premiumEyebrow: 'Coming soon', premiumTitle: 'Take your server one step further.', premiumText: 'Premium will bring advanced tools, deeper control, and special experiences for communities that want something extraordinary.', premiumStatus: 'In preparation', storyEyebrow: 'Made for people', storyTitle: 'Technology can feel personal.', storyText: 'Lylo brings your server essentials together with choices that are easy to understand and an interface that stays out of the conversation.', storyDetail: 'Connect your account, shape your community, and let the bot handle its part. You stay in control.', storyLink: 'Discover Lylo', closingEyebrow: 'A simple beginning', closingTitle: 'Your server deserves a bot that understands the room.', closingLink: 'Start with Lylo', terms: 'Terms', policy: 'Privacy policy' },
  fr: { navPremium: 'Premium✦', login: 'Se connecter', support: 'Assistance', logout: 'Se déconnecter', inviteButton: 'Ajouter bot', manageServers: 'Gérer les serveurs', heroText: 'La façon la plus simple de rendre votre communauté vivante, organisée et prête à grandir.', communityEyebrow: 'Une communauté qui grandit', communityTitle: 'Les communautés qui nous font confiance', communityLive: 'En direct', communityEmpty: 'Aucune communauté à afficher pour le moment.', communityMembers: 'Membres', featuresEyebrow: 'Tout ce dont votre communauté a besoin', featuresTitle: 'Plus de contrôle pour votre serveur. Plus de temps pour votre communauté.', featureOneTitle: 'Modération', featureOneText: 'Agissez rapidement lorsque des messages ou des situations perturbent votre serveur.', featureTwoTitle: 'AutoMod', featureTwoText: 'Bloquez automatiquement le spam, les liens dangereux et les mots interdits.', featureThreeTitle: 'Tickets', featureThreeText: 'Créez des espaces privés pour les demandes, les signalements et l’assistance.', featureFourTitle: 'Bienvenue', featureFourText: 'Accueillez chaque membre avec un message clair et des rôles automatiques.', featureFiveTitle: 'Départs', featureFiveText: 'Gardez votre serveur informé lorsqu’une personne quitte la communauté.', featureSixTitle: 'Rôles et communauté', featureSixText: 'Organisez les intérêts, les permissions et les accès de chacun.', premiumEyebrow: 'Bientôt', premiumTitle: 'Faites passer votre serveur au niveau supérieur.', premiumText: 'Premium réunira des outils avancés et des expériences spéciales pour les communautés ambitieuses.', premiumStatus: 'En préparation', storyEyebrow: 'Pensé pour les personnes', storyTitle: 'La technologie peut rester humaine.', storyText: 'Lylo rassemble les outils essentiels de votre serveur dans une interface claire qui laisse la conversation respirer.', storyDetail: 'Connectez votre compte, façonnez votre communauté et gardez le contrôle.', storyLink: 'Découvrir Lylo', closingEyebrow: 'Un début simple', closingTitle: 'Votre serveur mérite un bot qui comprend l’ambiance.', closingLink: 'Commencer avec Lylo', terms: 'Conditions', policy: 'Confidentialité' },
  pt: { navPremium: 'Premium✦', login: 'Entrar', support: 'Suporte', logout: 'Sair', inviteButton: 'Adicionar bot', manageServers: 'Gerenciar servidores', heroText: 'A forma mais simples de deixar sua comunidade viva, organizada e pronta para crescer.', communityEyebrow: 'Uma comunidade em crescimento', communityTitle: 'Comunidades que confiam em nós', communityLive: 'Ao vivo', communityEmpty: 'Ainda não há comunidades para mostrar.', communityMembers: 'Membros', featuresEyebrow: 'Tudo que sua comunidade precisa', featuresTitle: 'Mais controle para seu servidor. Mais tempo para sua comunidade.', featureOneTitle: 'Moderação', featureOneText: 'Aja rápido quando mensagens ou situações atrapalharem o ambiente do servidor.', featureTwoTitle: 'AutoMod', featureTwoText: 'Detecte spam, links perigosos e palavras bloqueadas automaticamente.', featureThreeTitle: 'Tickets', featureThreeText: 'Crie canais privados para suporte, denúncias e solicitações.', featureFourTitle: 'Boas-vindas', featureFourText: 'Receba cada pessoa com uma mensagem clara e cargos automáticos.', featureFiveTitle: 'Despedidas', featureFiveText: 'Mantenha o servidor informado quando alguém sair da comunidade.', featureSixTitle: 'Cargos e comunidade', featureSixText: 'Organize interesses, permissões e acessos para todos.', premiumEyebrow: 'Em breve', premiumTitle: 'Leve seu servidor além.', premiumText: 'Premium reunirá ferramentas avançadas e experiências especiais para comunidades que querem mais.', premiumStatus: 'Em preparação', storyEyebrow: 'Feito para pessoas', storyTitle: 'Tecnologia também pode ser próxima.', storyText: 'Lylo reúne as ferramentas importantes do seu servidor em uma interface clara e fácil de usar.', storyDetail: 'Conecte sua conta, organize sua comunidade e mantenha o controle.', storyLink: 'Conhecer Lylo', closingEyebrow: 'Um começo simples', closingTitle: 'Seu servidor merece um bot que entende o ambiente.', closingLink: 'Começar com Lylo', terms: 'Termos', policy: 'Privacidade' },
  id: { navPremium: 'Premium✦', login: 'Masuk', support: 'Dukungan', logout: 'Keluar', inviteButton: 'Tambahkan ke Discord', manageServers: 'Kelola server', heroText: 'Cara sederhana untuk membuat komunitasmu hidup, rapi, dan siap berkembang.', communityEyebrow: 'Komunitas yang terus berkembang', communityTitle: 'Komunitas yang mempercayai kami', communityLive: 'Langsung', communityEmpty: 'Belum ada komunitas untuk ditampilkan.', communityMembers: 'Anggota', featuresEyebrow: 'Semua yang komunitasmu butuhkan', featuresTitle: 'Lebih banyak kendali untuk server. Lebih banyak waktu untuk komunitas.', featureOneTitle: 'Moderasi', featureOneText: 'Bertindak cepat saat pesan atau situasi mengganggu server.', featureTwoTitle: 'AutoMod', featureTwoText: 'Deteksi spam, tautan berbahaya, dan kata terlarang secara otomatis.', featureThreeTitle: 'Tiket', featureThreeText: 'Buat kanal pribadi untuk dukungan, laporan, dan permintaan.', featureFourTitle: 'Sambutan', featureFourText: 'Sambut setiap anggota dengan pesan jelas dan peran otomatis.', featureFiveTitle: 'Perpisahan', featureFiveText: 'Beri tahu server saat seseorang meninggalkan komunitas.', featureSixTitle: 'Peran dan komunitas', featureSixText: 'Atur minat, izin, dan akses agar semua orang menemukan tempatnya.', premiumEyebrow: 'Segera hadir', premiumTitle: 'Bawa servermu lebih jauh.', premiumText: 'Premium akan menghadirkan alat lanjutan dan pengalaman khusus untuk komunitas yang ingin lebih.', premiumStatus: 'Dalam persiapan', storyEyebrow: 'Dibuat untuk manusia', storyTitle: 'Teknologi bisa terasa dekat.', storyText: 'Lylo menyatukan alat penting server dalam antarmuka yang jelas dan mudah dipahami.', storyDetail: 'Hubungkan akunmu, atur komunitasmu, dan tetap pegang kendali.', storyLink: 'Kenali Lylo', closingEyebrow: 'Awal yang sederhana', closingTitle: 'Servermu layak mendapatkan bot yang memahami suasana.', closingLink: 'Mulai dengan Lylo', terms: 'Ketentuan', policy: 'Privasi' },
  de: { navPremium: 'Premium✦', login: 'Anmelden', support: 'Support', logout: 'Abmelden', inviteButton: 'Zu Discord hinzufügen', manageServers: 'Server verwalten', heroText: 'Der einfachste Weg, deine Community lebendig, organisiert und bereit für Wachstum zu machen.', communityEyebrow: 'Eine wachsende Community', communityTitle: 'Communities, die uns vertrauen', communityLive: 'Live', communityEmpty: 'Noch gibt es keine Communities zu sehen.', communityMembers: 'Mitglieder', featuresEyebrow: 'Alles, was deine Community braucht', featuresTitle: 'Mehr Kontrolle für deinen Server. Mehr Zeit für deine Community.', featureOneTitle: 'Moderation', featureOneText: 'Reagiere schnell, wenn Nachrichten oder Situationen deinen Server stören.', featureTwoTitle: 'AutoMod', featureTwoText: 'Erkenne Spam, gefährliche Links und gesperrte Wörter automatisch.', featureThreeTitle: 'Tickets', featureThreeText: 'Erstelle private Kanäle für Support, Meldungen und Anfragen.', featureFourTitle: 'Willkommen', featureFourText: 'Begrüße jedes Mitglied mit einer klaren Nachricht und automatischen Rollen.', featureFiveTitle: 'Abschiede', featureFiveText: 'Informiere den Server, wenn jemand die Community verlässt.', featureSixTitle: 'Rollen und Community', featureSixText: 'Ordne Interessen, Berechtigungen und Zugänge übersichtlich.', premiumEyebrow: 'Demnächst', premiumTitle: 'Bring deinen Server weiter.', premiumText: 'Premium bietet fortgeschrittene Werkzeuge und besondere Erlebnisse für ambitionierte Communities.', premiumStatus: 'In Vorbereitung', storyEyebrow: 'Für Menschen gemacht', storyTitle: 'Technologie kann nahbar sein.', storyText: 'Lylo bündelt die wichtigsten Server-Werkzeuge in einer klaren Oberfläche, die dem Gespräch Raum lässt.', storyDetail: 'Verbinde dein Konto, gestalte deine Community und behalte die Kontrolle.', storyLink: 'Lylo entdecken', closingEyebrow: 'Ein einfacher Anfang', closingTitle: 'Dein Server verdient einen Bot, der die Stimmung versteht.', closingLink: 'Mit Lylo starten', terms: 'Bedingungen', policy: 'Datenschutz' }
};

const sharedTranslations = {
  es: {
    back: 'Volver', country: 'País', titleHome: 'Lylo | Discord bot', titleManage: 'Lylo | Gestionar servidores', titleConfig: 'Lylo | Configuración', titleLanguage: 'Lylo | Idioma del bot', titleTerms: 'Lylo | Términos', titlePolicy: 'Lylo | Política de privacidad', titlePremium: 'Lylo | Premium',
    languageTitle: 'País e idioma del bot', languageIntro: 'Elige un idioma para los comandos, respuestas y paneles de Lylo en uno de tus servidores.', languageChoose: 'Seleccionar idioma', languageServer: 'Seleccionar servidor', languageLoading: 'Cargando tus servidores...', languageChooseServer: 'Selecciona un servidor', languageNoServers: 'No tienes servidores propios', languageNoBot: 'Lylo no está añadido', languageServerNote: 'Solo aparecen servidores de los que eres propietario.', languageResetWarning: 'Al aplicar el idioma, se restablecerán los textos, roles y opciones personalizadas de tickets de ese servidor. Los bloqueos de usuarios se conservarán.', languageApply: 'Restablecer configuración y aplicar idioma', languageWorking: 'Aplicando idioma y restableciendo configuración...', languageConfirm: 'Esto restablecerá la configuración personalizada de tickets y permisos de este servidor. ¿Continuar?', languageOwnerError: 'Solo el propietario de este servidor puede cambiar el idioma.', languageChangeError: 'No se pudo cambiar el idioma.', languageDone: 'Idioma aplicado. La configuración personalizada se restableció y los comandos ya están sincronizados.', languageSaved: 'Idioma guardado y configuración restablecida. Los comandos se sincronizarán en la próxima actualización de Lylo.', languageNeedsBot: 'Idioma guardado y configuración restablecida. Los comandos se sincronizarán cuando añadas Lylo al servidor.', languageLoadError: 'No se pudieron cargar tus servidores.',
    termsUseHeading: 'Uso del servicio', termsUseText: 'Lylo es un bot para comunidades de Discord. Al añadirlo o utilizarlo aceptas usarlo de acuerdo con las reglas de Discord y las leyes aplicables.', termsResponsibilityHeading: 'Responsabilidad de la comunidad', termsResponsibilityText: 'Las personas administradoras de cada servidor son responsables de su configuración, permisos y del contenido compartido en su comunidad.', termsAvailabilityHeading: 'Disponibilidad', termsAvailabilityText: 'Trabajamos para mantener Lylo disponible, pero el servicio puede cambiar, pausarse o actualizarse cuando sea necesario.', termsContactHeading: 'Contacto', termsContactText: 'Para cualquier pregunta relacionada con estos términos, contacta al equipo de Lylo a través de los canales oficiales del proyecto.',
    policyInfoHeading: 'Información que utilizamos', policyInfoText: 'Lylo puede procesar la información mínima necesaria para funcionar dentro de Discord, como identificadores de servidor, canales y usuarios relacionados con sus funciones.', policyUseHeading: 'Cómo se utiliza', policyUseText: 'La información se utiliza únicamente para ofrecer, mantener y mejorar las funciones del bot. No vendemos información personal.', policyRetentionHeading: 'Conservación', policyRetentionText: 'Conservamos los datos solo durante el tiempo necesario para la función correspondiente o cuando la ley lo exige.', policyOptionsHeading: 'Tus opciones', policyOptionsText: 'Las personas administradoras pueden retirar a Lylo de su servidor. Para solicitar información o resolver una duda de privacidad, contacta al equipo del proyecto.'
  },
  en: {
    back: 'Back', country: 'Country', titleHome: 'Lylo | Discord bot', titleManage: 'Lylo | Manage servers', titleConfig: 'Lylo | Settings', titleLanguage: 'Lylo | Bot language', titleTerms: 'Lylo | Terms', titlePolicy: 'Lylo | Privacy policy', titlePremium: 'Lylo | Premium',
    languageTitle: 'Country and bot language', languageIntro: 'Choose a language for Lylo commands, replies, and panels on one of your servers.', languageChoose: 'Choose a language', languageServer: 'Choose a server', languageLoading: 'Loading your servers...', languageChooseServer: 'Select a server', languageNoServers: 'You do not own any servers', languageNoBot: 'Lylo is not added', languageServerNote: 'Only servers you own are shown.', languageResetWarning: 'Applying a language resets that server’s custom ticket text, roles, and options. User blocks are kept.', languageApply: 'Reset settings and apply language', languageWorking: 'Applying language and resetting settings...', languageConfirm: 'This will reset this server’s custom ticket and permission settings. Continue?', languageOwnerError: 'Only this server’s owner can change its language.', languageChangeError: 'Could not change the language.', languageDone: 'Language applied. Custom settings were reset and commands are synchronized.', languageSaved: 'Language saved and settings reset. Commands will sync during Lylo’s next update.', languageNeedsBot: 'Language saved and settings reset. Commands will sync after Lylo is added to the server.', languageLoadError: 'Could not load your servers.',
    termsUseHeading: 'Use of the service', termsUseText: 'Lylo is a bot for Discord communities. By adding or using it, you agree to follow Discord’s rules and applicable laws.', termsResponsibilityHeading: 'Community responsibility', termsResponsibilityText: 'Server administrators are responsible for their settings, permissions, and the content shared in their community.', termsAvailabilityHeading: 'Availability', termsAvailabilityText: 'We work to keep Lylo available, but the service may change, pause, or update when needed.', termsContactHeading: 'Contact', termsContactText: 'For questions about these terms, contact the Lylo team through the project’s official channels.',
    policyInfoHeading: 'Information we use', policyInfoText: 'Lylo may process the minimum information needed to work in Discord, such as server, channel, and user IDs related to its features.', policyUseHeading: 'How it is used', policyUseText: 'Information is used only to provide, maintain, and improve bot features. We do not sell personal information.', policyRetentionHeading: 'Retention', policyRetentionText: 'We keep data only as long as needed for the relevant feature or when required by law.', policyOptionsHeading: 'Your choices', policyOptionsText: 'Server administrators can remove Lylo from their server. For information or privacy questions, contact the project team.'
  },
  fr: {
    back: 'Retour', country: 'Pays', titleHome: 'Lylo | Bot Discord', titleManage: 'Lylo | Gérer les serveurs', titleConfig: 'Lylo | Configuration', titleLanguage: 'Lylo | Langue du bot', titleTerms: 'Lylo | Conditions', titlePolicy: 'Lylo | Confidentialité', titlePremium: 'Lylo | Premium',
    languageTitle: 'Pays et langue du bot', languageIntro: 'Choisissez la langue des commandes, réponses et panneaux de Lylo pour un de vos serveurs.', languageChoose: 'Choisir une langue', languageServer: 'Choisir un serveur', languageLoading: 'Chargement de vos serveurs...', languageChooseServer: 'Sélectionnez un serveur', languageNoServers: 'Vous ne possédez aucun serveur', languageNoBot: 'Lylo n’est pas ajouté', languageServerNote: 'Seuls les serveurs dont vous êtes propriétaire sont affichés.', languageResetWarning: 'Appliquer une langue réinitialise les textes, rôles et options personnalisés des tickets de ce serveur. Les blocages sont conservés.', languageApply: 'Réinitialiser et appliquer la langue', languageWorking: 'Application de la langue et réinitialisation...', languageConfirm: 'Cela réinitialisera les textes et permissions personnalisés des tickets de ce serveur. Continuer ?', languageOwnerError: 'Seul le propriétaire de ce serveur peut changer sa langue.', languageChangeError: 'Impossible de changer la langue.', languageDone: 'Langue appliquée. Les réglages personnalisés ont été réinitialisés et les commandes synchronisées.', languageSaved: 'Langue enregistrée et réglages réinitialisés. Les commandes seront synchronisées à la prochaine mise à jour de Lylo.', languageNeedsBot: 'Langue enregistrée et réglages réinitialisés. Les commandes seront synchronisées après l’ajout de Lylo au serveur.', languageLoadError: 'Impossible de charger vos serveurs.',
    termsUseHeading: 'Utilisation du service', termsUseText: 'Lylo est un bot destiné aux communautés Discord. En l’ajoutant ou en l’utilisant, vous acceptez de respecter les règles de Discord et les lois applicables.', termsResponsibilityHeading: 'Responsabilité de la communauté', termsResponsibilityText: 'Les administrateurs de chaque serveur sont responsables de sa configuration, de ses permissions et du contenu partagé dans leur communauté.', termsAvailabilityHeading: 'Disponibilité', termsAvailabilityText: 'Nous faisons le nécessaire pour maintenir Lylo disponible, mais le service peut évoluer, être suspendu ou mis à jour si besoin.', termsContactHeading: 'Contact', termsContactText: 'Pour toute question concernant ces conditions, contactez l’équipe Lylo via les canaux officiels du projet.',
    policyInfoHeading: 'Informations utilisées', policyInfoText: 'Lylo peut traiter les informations minimales nécessaires à son fonctionnement sur Discord, comme les identifiants des serveurs, salons et utilisateurs liés à ses fonctions.', policyUseHeading: 'Utilisation des données', policyUseText: 'Les informations servent uniquement à fournir, maintenir et améliorer les fonctions du bot. Nous ne vendons pas de données personnelles.', policyRetentionHeading: 'Conservation', policyRetentionText: 'Nous conservons les données uniquement le temps nécessaire à la fonction concernée ou lorsque la loi l’exige.', policyOptionsHeading: 'Vos choix', policyOptionsText: 'Les administrateurs peuvent retirer Lylo de leur serveur. Pour toute demande d’information ou question de confidentialité, contactez l’équipe du projet.'
  },
  pt: {
    back: 'Voltar', country: 'País', titleHome: 'Lylo | Bot do Discord', titleManage: 'Lylo | Gerenciar servidores', titleConfig: 'Lylo | Configuração', titleLanguage: 'Lylo | Idioma do bot', titleTerms: 'Lylo | Termos', titlePolicy: 'Lylo | Privacidade', titlePremium: 'Lylo | Premium',
    languageTitle: 'País e idioma do bot', languageIntro: 'Escolha o idioma dos comandos, respostas e painéis do Lylo em um dos seus servidores.', languageChoose: 'Selecionar idioma', languageServer: 'Selecionar servidor', languageLoading: 'Carregando seus servidores...', languageChooseServer: 'Selecione um servidor', languageNoServers: 'Você não possui servidores', languageNoBot: 'Lylo não foi adicionado', languageServerNote: 'Somente servidores dos quais você é proprietário aparecem.', languageResetWarning: 'Aplicar o idioma redefinirá textos, cargos e opções personalizadas de tickets deste servidor. Os bloqueios serão mantidos.', languageApply: 'Redefinir configuração e aplicar idioma', languageWorking: 'Aplicando idioma e redefinindo configurações...', languageConfirm: 'Isso redefinirá as configurações personalizadas de tickets e permissões deste servidor. Continuar?', languageOwnerError: 'Somente o proprietário deste servidor pode alterar o idioma.', languageChangeError: 'Não foi possível alterar o idioma.', languageDone: 'Idioma aplicado. As configurações personalizadas foram redefinidas e os comandos sincronizados.', languageSaved: 'Idioma salvo e configurações redefinidas. Os comandos serão sincronizados na próxima atualização do Lylo.', languageNeedsBot: 'Idioma salvo e configurações redefinidas. Os comandos serão sincronizados quando o Lylo for adicionado ao servidor.', languageLoadError: 'Não foi possível carregar seus servidores.',
    termsUseHeading: 'Uso do serviço', termsUseText: 'Lylo é um bot para comunidades do Discord. Ao adicioná-lo ou usá-lo, você concorda em seguir as regras do Discord e as leis aplicáveis.', termsResponsibilityHeading: 'Responsabilidade da comunidade', termsResponsibilityText: 'Os administradores de cada servidor são responsáveis pelas configurações, permissões e conteúdo compartilhado na comunidade.', termsAvailabilityHeading: 'Disponibilidade', termsAvailabilityText: 'Trabalhamos para manter o Lylo disponível, mas o serviço pode mudar, pausar ou ser atualizado quando necessário.', termsContactHeading: 'Contato', termsContactText: 'Para dúvidas sobre estes termos, fale com a equipe Lylo pelos canais oficiais do projeto.',
    policyInfoHeading: 'Informações utilizadas', policyInfoText: 'O Lylo pode processar as informações mínimas necessárias para funcionar no Discord, como IDs de servidores, canais e usuários relacionados aos seus recursos.', policyUseHeading: 'Como usamos', policyUseText: 'As informações são usadas somente para oferecer, manter e melhorar os recursos do bot. Não vendemos informações pessoais.', policyRetentionHeading: 'Retenção', policyRetentionText: 'Mantemos os dados somente pelo tempo necessário para o recurso correspondente ou quando exigido por lei.', policyOptionsHeading: 'Suas opções', policyOptionsText: 'Administradores podem remover o Lylo do servidor. Para solicitar informações ou tirar dúvidas de privacidade, fale com a equipe do projeto.'
  },
  id: {
    back: 'Kembali', country: 'Negara', titleHome: 'Lylo | Bot Discord', titleManage: 'Lylo | Kelola server', titleConfig: 'Lylo | Pengaturan', titleLanguage: 'Lylo | Bahasa bot', titleTerms: 'Lylo | Ketentuan', titlePolicy: 'Lylo | Kebijakan privasi', titlePremium: 'Lylo | Premium',
    languageTitle: 'Negara dan bahasa bot', languageIntro: 'Pilih bahasa untuk perintah, balasan, dan panel Lylo di salah satu servermu.', languageChoose: 'Pilih bahasa', languageServer: 'Pilih server', languageLoading: 'Memuat servermu...', languageChooseServer: 'Pilih server', languageNoServers: 'Kamu tidak memiliki server', languageNoBot: 'Lylo belum ditambahkan', languageServerNote: 'Hanya server milikmu yang ditampilkan.', languageResetWarning: 'Menerapkan bahasa akan mengatur ulang teks, peran, dan opsi tiket khusus server ini. Pemblokiran pengguna tetap disimpan.', languageApply: 'Atur ulang pengaturan dan terapkan bahasa', languageWorking: 'Menerapkan bahasa dan mengatur ulang pengaturan...', languageConfirm: 'Pengaturan tiket dan izin khusus server ini akan diatur ulang. Lanjutkan?', languageOwnerError: 'Hanya pemilik server ini yang dapat mengubah bahasanya.', languageChangeError: 'Bahasa tidak dapat diubah.', languageDone: 'Bahasa diterapkan. Pengaturan khusus diatur ulang dan perintah disinkronkan.', languageSaved: 'Bahasa disimpan dan pengaturan diatur ulang. Perintah akan disinkronkan pada pembaruan Lylo berikutnya.', languageNeedsBot: 'Bahasa disimpan dan pengaturan diatur ulang. Perintah akan disinkronkan setelah Lylo ditambahkan ke server.', languageLoadError: 'Server tidak dapat dimuat.',
    termsUseHeading: 'Penggunaan layanan', termsUseText: 'Lylo adalah bot untuk komunitas Discord. Dengan menambahkan atau menggunakannya, kamu setuju untuk mengikuti aturan Discord dan hukum yang berlaku.', termsResponsibilityHeading: 'Tanggung jawab komunitas', termsResponsibilityText: 'Admin server bertanggung jawab atas pengaturan, izin, dan konten yang dibagikan di komunitas mereka.', termsAvailabilityHeading: 'Ketersediaan', termsAvailabilityText: 'Kami berupaya menjaga Lylo tetap tersedia, tetapi layanan dapat berubah, dijeda, atau diperbarui bila diperlukan.', termsContactHeading: 'Kontak', termsContactText: 'Untuk pertanyaan tentang ketentuan ini, hubungi tim Lylo melalui kanal resmi proyek.',
    policyInfoHeading: 'Informasi yang digunakan', policyInfoText: 'Lylo dapat memproses informasi minimum yang diperlukan untuk bekerja di Discord, seperti ID server, kanal, dan pengguna yang terkait dengan fiturnya.', policyUseHeading: 'Cara penggunaan', policyUseText: 'Informasi hanya digunakan untuk menyediakan, menjaga, dan meningkatkan fitur bot. Kami tidak menjual informasi pribadi.', policyRetentionHeading: 'Penyimpanan', policyRetentionText: 'Data disimpan hanya selama diperlukan untuk fitur terkait atau jika diwajibkan oleh hukum.', policyOptionsHeading: 'Pilihanmu', policyOptionsText: 'Admin dapat menghapus Lylo dari server. Untuk meminta informasi atau bertanya tentang privasi, hubungi tim proyek.'
  },
  de: {
    back: 'Zurück', country: 'Land', titleHome: 'Lylo | Discord-Bot', titleManage: 'Lylo | Server verwalten', titleConfig: 'Lylo | Einstellungen', titleLanguage: 'Lylo | Bot-Sprache', titleTerms: 'Lylo | Bedingungen', titlePolicy: 'Lylo | Datenschutz', titlePremium: 'Lylo | Premium',
    languageTitle: 'Land und Bot-Sprache', languageIntro: 'Wähle eine Sprache für Lylo-Befehle, Antworten und Panels auf einem deiner Server.', languageChoose: 'Sprache auswählen', languageServer: 'Server auswählen', languageLoading: 'Server werden geladen...', languageChooseServer: 'Server auswählen', languageNoServers: 'Du besitzt keine Server', languageNoBot: 'Lylo wurde nicht hinzugefügt', languageServerNote: 'Es werden nur Server angezeigt, deren Inhaber du bist.', languageResetWarning: 'Beim Anwenden der Sprache werden benutzerdefinierte Tickettexte, Rollen und Optionen dieses Servers zurückgesetzt. Benutzersperren bleiben erhalten.', languageApply: 'Einstellungen zurücksetzen und Sprache anwenden', languageWorking: 'Sprache wird angewendet und Einstellungen werden zurückgesetzt...', languageConfirm: 'Die benutzerdefinierten Ticket- und Berechtigungseinstellungen dieses Servers werden zurückgesetzt. Fortfahren?', languageOwnerError: 'Nur der Serverinhaber kann die Sprache ändern.', languageChangeError: 'Die Sprache konnte nicht geändert werden.', languageDone: 'Sprache angewendet. Einstellungen wurden zurückgesetzt und Befehle synchronisiert.', languageSaved: 'Sprache gespeichert und Einstellungen zurückgesetzt. Befehle werden beim nächsten Lylo-Update synchronisiert.', languageNeedsBot: 'Sprache gespeichert und Einstellungen zurückgesetzt. Befehle werden synchronisiert, sobald Lylo zum Server hinzugefügt wurde.', languageLoadError: 'Server konnten nicht geladen werden.',
    termsUseHeading: 'Nutzung des Dienstes', termsUseText: 'Lylo ist ein Bot für Discord-Communities. Durch das Hinzufügen oder Verwenden stimmst du zu, die Discord-Regeln und geltende Gesetze einzuhalten.', termsResponsibilityHeading: 'Verantwortung der Community', termsResponsibilityText: 'Serveradministratoren sind für Einstellungen, Berechtigungen und geteilte Inhalte ihrer Community verantwortlich.', termsAvailabilityHeading: 'Verfügbarkeit', termsAvailabilityText: 'Wir bemühen uns, Lylo verfügbar zu halten. Der Dienst kann bei Bedarf geändert, pausiert oder aktualisiert werden.', termsContactHeading: 'Kontakt', termsContactText: 'Bei Fragen zu diesen Bedingungen kontaktiere das Lylo-Team über die offiziellen Projektkanäle.',
    policyInfoHeading: 'Verwendete Informationen', policyInfoText: 'Lylo kann die für Discord erforderlichen Mindestinformationen verarbeiten, etwa Server-, Kanal- und Benutzer-IDs im Zusammenhang mit seinen Funktionen.', policyUseHeading: 'Verwendung', policyUseText: 'Informationen dienen ausschließlich dazu, Bot-Funktionen bereitzustellen, zu warten und zu verbessern. Wir verkaufen keine personenbezogenen Daten.', policyRetentionHeading: 'Speicherung', policyRetentionText: 'Daten werden nur so lange gespeichert, wie es für die jeweilige Funktion nötig oder gesetzlich vorgeschrieben ist.', policyOptionsHeading: 'Deine Möglichkeiten', policyOptionsText: 'Administratoren können Lylo von ihrem Server entfernen. Bei Fragen zu Informationen oder Datenschutz kontaktiere das Projektteam.'
  }
};

const accessibilityTranslations = {
  es: { backHomeAria: 'Volver a la página principal', mainNavigationAria: 'Navegación principal', botLanguageAria: 'Idioma del bot', premiumPlansAria: 'Planes Premium', title404: 'Lylo | Página no encontrada' },
  en: { backHomeAria: 'Back to the home page', mainNavigationAria: 'Main navigation', botLanguageAria: 'Bot language', premiumPlansAria: 'Premium plans', title404: 'Lylo | Page not found' },
  fr: { backHomeAria: 'Retour à la page d’accueil', mainNavigationAria: 'Navigation principale', botLanguageAria: 'Langue du bot', premiumPlansAria: 'Offres Premium', title404: 'Lylo | Page introuvable' },
  pt: { backHomeAria: 'Voltar para a página inicial', mainNavigationAria: 'Navegação principal', botLanguageAria: 'Idioma do bot', premiumPlansAria: 'Planos Premium', title404: 'Lylo | Página não encontrada' },
  id: { backHomeAria: 'Kembali ke halaman utama', mainNavigationAria: 'Navigasi utama', botLanguageAria: 'Bahasa bot', premiumPlansAria: 'Paket Premium', title404: 'Lylo | Halaman tidak ditemukan' },
  de: { backHomeAria: 'Zurück zur Startseite', mainNavigationAria: 'Hauptnavigation', botLanguageAria: 'Bot-Sprache', premiumPlansAria: 'Premium-Tarife', title404: 'Lylo | Seite nicht gefunden' }
};

const picker = document.querySelector('.language-picker');
const menu = document.querySelector('.language-menu');
const toggle = document.querySelector('.language-toggle');
const storedLanguage = localStorage.getItem('lylo-site-language') || localStorage.getItem('lylo-language') || 'es';
const accountMenu = document.querySelector('[data-account-menu]');
const loginLink = document.querySelector('[data-login-link]');
const accountToggle = document.querySelector('.account-toggle');
const accountDropdown = document.querySelector('.account-dropdown');
const accountAvatarElements = document.querySelectorAll('[data-account-avatar]');
const accountName = document.querySelector('[data-account-name]');
const manageServersButton = document.querySelector('[data-manage-servers]');
const defaultAvatar = 'BOTIMAGEN.png';

function renderMenu(currentCode) {
  menu.innerHTML = languages.map((language) => `<button class="language-option ${language.code === currentCode ? 'selected' : ''}" role="menuitem" type="button" data-language="${language.code}"><span>${language.flag}</span><span>${language.label}</span></button>`).join('');
  menu.querySelectorAll('.language-option').forEach((option) => option.addEventListener('click', () => setLanguage(option.dataset.language)));
}

function applySiteLanguage(code) {
  const language = languages.find((item) => item.code === code) || languages[2];
  const copy = { ...completeTranslations.es, ...translations[language.code], ...completeTranslations[language.code], ...legalTranslations[language.code], ...sharedTranslations[language.code], ...accessibilityTranslations[language.code] };
  document.documentElement.lang = language.code;
  document.querySelectorAll('[data-i18n]').forEach((element) => { if (copy[element.dataset.i18n]) element.textContent = copy[element.dataset.i18n]; });
  document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => { if (copy[element.dataset.i18nPlaceholder]) element.placeholder = copy[element.dataset.i18nPlaceholder]; });
  document.querySelectorAll('[data-i18n-title]').forEach((element) => { if (copy[element.dataset.i18nTitle]) element.title = copy[element.dataset.i18nTitle]; });
  document.querySelectorAll('[data-i18n-aria-label]').forEach((element) => { if (copy[element.dataset.i18nAriaLabel]) element.setAttribute('aria-label', copy[element.dataset.i18nAriaLabel]); });
  const pageTitle = document.querySelector('title[data-i18n]');
  if (pageTitle && copy[pageTitle.dataset.i18n]) pageTitle.textContent = copy[pageTitle.dataset.i18n];
  const currentFlag = document.querySelector('.current-flag');
  const currentLanguage = document.querySelector('.current-language');
  if (currentFlag) currentFlag.textContent = language.flag;
  if (currentLanguage) currentLanguage.textContent = language.code.toUpperCase();
  if (menu) renderMenu(language.code);
}

function setLanguage(code) {
  const language = languages.find((item) => item.code === code) || languages[2];
  applySiteLanguage(language.code);
  localStorage.setItem('lylo-site-language', language.code);
  document.dispatchEvent(new CustomEvent('lylo-language-change', { detail: language.code }));
  if (picker) picker.classList.remove('open');
  if (toggle) toggle.setAttribute('aria-expanded', 'false');
}

const languageResetCopy = {
  es: { languageResetWarning: 'Al cambiar el idioma se restablece toda la configuración del servidor: tickets, AutoMod, honeypot, bienvenidas, autorol y bloqueos.', languageApply: 'Restablecer todo y aplicar idioma', languageWorking: 'Restableciendo toda la configuración y aplicando idioma...', languageConfirm: 'Esto restablecerá tickets, AutoMod, honeypot, bienvenidas, autorol y bloqueos de este servidor. ¿Continuar?', languageDone: 'Idioma aplicado y configuración restablecida.', languageSaved: 'Idioma guardado y configuración restablecida. Los comandos se sincronizarán en la próxima actualización de Lylo.', languageNeedsBot: 'Idioma guardado y configuración restablecida. Los comandos se sincronizarán cuando añadas Lylo al servidor.' },
  en: { languageResetWarning: 'Changing the language resets all settings for this server: tickets, AutoMod, honeypot, welcomes, auto-role, and blocks.', languageApply: 'Reset all and apply language', languageWorking: 'Resetting all settings and applying language...', languageConfirm: 'This resets tickets, AutoMod, honeypot, welcomes, auto-role, and blocks for this server. Continue?', languageDone: 'Language applied and settings reset.', languageSaved: 'Language saved and settings reset. Commands will sync during Lylo’s next update.', languageNeedsBot: 'Language saved and settings reset. Commands will sync after Lylo is added to the server.' },
  fr: { languageResetWarning: 'Changer la langue réinitialise tous les réglages du serveur : tickets, AutoMod, honeypot, accueils, rôles automatiques et blocages.', languageApply: 'Tout réinitialiser et appliquer', languageWorking: 'Réinitialisation des réglages et application de la langue...', languageConfirm: 'Cette action réinitialise les tickets, AutoMod, honeypot, accueils, rôles automatiques et blocages de ce serveur. Continuer ?', languageDone: 'Langue appliquée et réglages réinitialisés.', languageSaved: 'Langue enregistrée et réglages réinitialisés. Les commandes seront synchronisées à la prochaine mise à jour.', languageNeedsBot: 'Langue enregistrée et réglages réinitialisés. Les commandes seront synchronisées après l’ajout de Lylo.' },
  pt: { languageResetWarning: 'Alterar o idioma redefine todas as configurações do servidor: tickets, AutoMod, honeypot, boas-vindas, cargos automáticos e bloqueios.', languageApply: 'Redefinir tudo e aplicar idioma', languageWorking: 'Redefinindo todas as configurações e aplicando o idioma...', languageConfirm: 'Isso redefine tickets, AutoMod, honeypot, boas-vindas, cargos automáticos e bloqueios deste servidor. Continuar?', languageDone: 'Idioma aplicado e configurações redefinidas.', languageSaved: 'Idioma salvo e configurações redefinidas. Os comandos serão sincronizados na próxima atualização.', languageNeedsBot: 'Idioma salvo e configurações redefinidas. Os comandos serão sincronizados quando Lylo for adicionado ao servidor.' },
  id: { languageResetWarning: 'Mengubah bahasa akan mengatur ulang semua pengaturan server: tiket, AutoMod, honeypot, sambutan, peran otomatis, dan pemblokiran.', languageApply: 'Atur ulang semua dan terapkan bahasa', languageWorking: 'Mengatur ulang semua pengaturan dan menerapkan bahasa...', languageConfirm: 'Tiket, AutoMod, honeypot, sambutan, peran otomatis, dan pemblokiran server ini akan diatur ulang. Lanjutkan?', languageDone: 'Bahasa diterapkan dan pengaturan diatur ulang.', languageSaved: 'Bahasa disimpan dan pengaturan diatur ulang. Perintah akan disinkronkan pada pembaruan Lylo berikutnya.', languageNeedsBot: 'Bahasa disimpan dan pengaturan diatur ulang. Perintah akan disinkronkan setelah Lylo ditambahkan ke server.' },
  de: { languageResetWarning: 'Beim Sprachwechsel werden alle Servereinstellungen zurückgesetzt: Tickets, AutoMod, Honeypot, Begrüßungen, automatische Rollen und Sperren.', languageApply: 'Alles zurücksetzen und Sprache anwenden', languageWorking: 'Alle Einstellungen werden zurückgesetzt und die Sprache wird angewendet...', languageConfirm: 'Tickets, AutoMod, Honeypot, Begrüßungen, automatische Rollen und Sperren dieses Servers werden zurückgesetzt. Fortfahren?', languageDone: 'Sprache angewendet und Einstellungen zurückgesetzt.', languageSaved: 'Sprache gespeichert und Einstellungen zurückgesetzt. Befehle werden beim nächsten Lylo-Update synchronisiert.', languageNeedsBot: 'Sprache gespeichert und Einstellungen zurückgesetzt. Befehle werden synchronisiert, sobald Lylo zum Server hinzugefügt wurde.' }
};

window.lyloTranslate = (key, code = document.documentElement.lang) => languageResetCopy[code]?.[key] || sharedTranslations[code]?.[key] || sharedTranslations.es[key] || key;
document.addEventListener('lylo-language-change', (event) => applySiteLanguage(event.detail));
document.addEventListener('lylo-language-change', (event) => {
  const copy = languageResetCopy[event.detail] || languageResetCopy.es;
  document.querySelectorAll('[data-i18n]').forEach((element) => {
    if (copy[element.dataset.i18n]) element.textContent = copy[element.dataset.i18n];
  });
});

if (toggle && picker) {
  toggle.addEventListener('click', () => { const open = picker.classList.toggle('open'); toggle.setAttribute('aria-expanded', String(open)); });
  document.addEventListener('click', (event) => { if (!picker.contains(event.target)) { picker.classList.remove('open'); toggle.setAttribute('aria-expanded', 'false'); } });
}

function renderAccount(user) {
  if (manageServersButton) manageServersButton.hidden = !user;
  if (!accountMenu) return;
  if (!user) {
    loginLink.hidden = false;
    accountToggle.hidden = true;
    accountDropdown.hidden = true;
    return;
  }
  loginLink.hidden = true;
  accountToggle.hidden = false;
  accountAvatarElements.forEach((image) => { image.src = user.avatar || defaultAvatar; image.alt = user.username || 'Discord account'; });
  accountName.textContent = user.username || 'Discord user';
}

if (accountToggle) {
  accountToggle.addEventListener('click', () => {
    const isOpen = !accountDropdown.hidden;
    accountDropdown.hidden = isOpen;
    accountToggle.setAttribute('aria-expanded', String(!isOpen));
  });
  document.querySelector('[data-logout]').addEventListener('click', () => {
    fetch('/auth/logout', { method: 'POST' }).finally(() => {
      accountDropdown.hidden = true;
      accountToggle.setAttribute('aria-expanded', 'false');
      renderAccount(null);
    });
  });
  document.addEventListener('click', (event) => {
    if (!accountMenu.contains(event.target)) {
      accountDropdown.hidden = true;
      accountToggle.setAttribute('aria-expanded', 'false');
    }
  });
}

setLanguage(storedLanguage);
fetch('/api/me').then((response) => response.json()).then(({ user }) => renderAccount(user)).catch(() => renderAccount(null));

const revealObserver = window.matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)
  ? null
  : new IntersectionObserver((entries, observer) => {
    entries.forEach((entry) => {
      if (!entry.isIntersecting) return;
      entry.target.classList.add('is-visible');
      observer.unobserve(entry.target);
    });
  }, { rootMargin: '0px 0px -8% 0px', threshold: 0.12 });

function revealVisibleElements() {
  const visibleTop = window.innerHeight * 0.92;
  const visibleBottom = window.innerHeight * 0.08;
  document.querySelectorAll('.scroll-reveal:not(.is-visible)').forEach((element) => {
    const bounds = element.getBoundingClientRect();
    if (bounds.top < visibleTop && bounds.bottom > visibleBottom && bounds.left < window.innerWidth && bounds.right > 0) {
      element.classList.add('is-visible');
    }
  });
}

function observeScrollReveals() {
  if (!revealObserver) return;
  const revealTargets = document.querySelectorAll('main > section, .hero-reference-content, .feature-item, .plan-card, .premium-hero, .premium-footnote, .manage-heading, .server-search, .server-state, .server-card, .config-heading, .config-note, .config-section, .config-preview, .language-heading, .language-section, .language-reset-warning, .legal-page > .eyebrow, .legal-page > h1, .legal-page > h2, .legal-page > p, .legal-page > .back-link, .error-content > *');
  revealTargets.forEach((element, index) => {
    if (element.classList.contains('scroll-reveal')) return;
    element.classList.add('scroll-reveal');
    element.style.setProperty('--reveal-delay', `${Math.min(index % 7, 6) * 75}ms`);
    if (element.matches('.feature-item, .plan-card, .server-card, .config-section')) element.style.setProperty('--reveal-x', index % 2 ? '18px' : '-18px');
    revealObserver.observe(element);
  });
  revealVisibleElements();
}

observeScrollReveals();
window.addEventListener('scroll', revealVisibleElements, { passive: true });
window.addEventListener('resize', revealVisibleElements);
document.addEventListener('visibilitychange', revealVisibleElements);
if (revealObserver && document.body) {
  new MutationObserver((records) => {
    if (records.some((record) => record.addedNodes.length)) observeScrollReveals();
  }).observe(document.body, { childList: true, subtree: true });
}

const communitiesGrid = document.querySelector('[data-communities-grid]');
const communityEmpty = document.querySelector('[data-community-empty]');
const communityLogo = 'https://cdn.discordapp.com/embed/avatars/0.png';

function escapeHtml(value) {
  return String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
}

function renderCommunities(communities) {
  if (!communitiesGrid) return;
  if (!communities.length) {
    communitiesGrid.innerHTML = '';
    communityEmpty.hidden = false;
    communitiesGrid.appendChild(communityEmpty);
    return;
  }
  communityEmpty.hidden = true;
  const membersLabel = (communityTranslations[document.documentElement.lang] || communityTranslations.es).communityMembers;
  const cards = communities.map((community) => `<article class="community-card"><img src="${community.icon || communityLogo}" alt="${escapeHtml(community.name)}"><div><h3>${escapeHtml(community.name)}</h3><p>${Number(community.memberCount).toLocaleString(document.documentElement.lang)} <span>${membersLabel}</span></p></div></article>`).join('');
  communitiesGrid.innerHTML = cards + cards;
}

async function loadCommunities() {
  if (!communitiesGrid) return;
  try {
    const response = await fetch('/api/communities');
    const data = await response.json();
    renderCommunities(data.communities || []);
  } catch {
    renderCommunities([]);
  }
}

loadCommunities();
document.addEventListener('lylo-language-change', loadCommunities);
window.setInterval(loadCommunities, 5000);
